version: '3'
services:
  web:
    build: .
    image: vocqgen-streamlit:latest
    restart: unless-stopped
    volumes:
      - ./.streamlit:/app/.streamlit
    ports:
      - 8501:8501
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
