# Merriam-Webster API key: https://dictionaryapi.com/
DICT_API_KEY = "YOUR_Merriam_Webster_API_KEY"

# Supported gpt models
MODEL_LIST = ["gpt-4o", "gpt-4o-mini", "gpt-4-1106-preview", "gpt-4", "gpt-3.5-turbo",]
